name: Laravel

on:
  push:
  pull_request:

env:
  DB_USERNAME: sail
  DB_PASSWORD: password
  MAIL_FROM_ADDRESS: info@example.com

jobs:
   phpunit:
     runs-on: ubuntu-latest

     services:
       mysql.test:
         image: 'mysql/mysql-server:8.0'
         ports:
           - 3306:3306
         env:
           MYSQL_ROOT_PASSWORD: root_password
           MYSQL_DATABASE: ${{ env.DB_DATABASE }}
           MYSQL_USER: ${{ env.DB_USERNAME }}
           MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
           MYSQL_ROOT_HOST: '%'
         options: >-
           --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
           --health-interval=10s
           --health-timeout=5s
           --health-retries=5

     steps:
       - name: Checkout Code
         uses: actions/checkout@v2

       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
           php-version: '8.1'
           tools: composer:v2

       - name: Copy .env for Testing
         run: cp .env.example .env.testing

       - name: Install Dependencies
         run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

       - name: Set Hostname for MySQL
         run: echo "127.0.0.1 mysql.test" | sudo tee -a /etc/hosts

       - name: Configure Database Permissions
         run: |
           mysql -h mysql.test -uroot -proot_password -e "CREATE USER IF NOT EXISTS 'sail'@'%' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON . TO 'sail'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"

       - name: Generate Application Key
         run: php artisan key:generate --env=testing

       - name: Run Migrations
         run: php artisan migrate --env=testing --force

       - name: Execute Tests
         run: vendor/bin/phpunit
